server {
    listen 80;
    listen [::]:80;
    server_name ersr.baby www.ersr.baby;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ersr.baby www.ersr.baby;

    ssl_certificate /keys/ersr_baby_chain.crt;
    ssl_certificate_key /keys/ersr.key;

    root /var/www/ersr;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
